logging.level:
  org.springframework.data.r2dbc: DEBUG

spring:

  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
#          use_query_cache: true
#          use_native_client: true
#          use_minimal_puts: true
          generate_statistics: true
#                    com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory
#          com.hazelcast.hibernate.HazelcastCacheRegionFactory
          region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
          hazelcast.instance_name: hazelcastInstance
#          hazelcast.shutdown_on_session_factory_close: false
      jakarta.persistence.sharedCache.mode: ENABLE_SELECTIVE


  h2:
    console:
      enabled: true
